# Generated by Django 4.2.1 on 2023-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_users',
            field=models.BooleanField(default=False),
        ),
    ]
